### ISSUE TITLE
Unable to pull from ACR after deploying a second cluster

### ISSUE THREAD

**Issue by joaquinrz** [mspnp/aks-baseline-multi-region#46]
I am having some issues when pulling from ACR in my cluster.

Steps to reproduce:
- Deploy the shared services and `az acr import` my custom image to ACR
- Deploy cluster A and manually apply my yaml file (here ACR pull is successful)
- Deploy cluster B and manually apply my yaml file (here ACR pul is succsful)
- Go back to cluster A and delete the pod of my app, which would trigger the pod to recreate and attempt to pull the image again, which would fail. Seems to be that DNS is no longer resolving my registry `acraksmemilf46kr3qe.azurecr.io` 

``` 
Warning  Failed     37m (x4 over 38m)      kubelet, aks-npuser01-42199627-vmss000001  Failed to pull image "acraksmemilf46kr3qe.azurecr.io/retaildevcrews/ngsa-lr:beta": rpc error: code = Unknown desc = failed to pull and unpack image "acraksmemilf46kr3qe.azurecr.io/retaildevcrews/ngsa-lr:beta": failed to reso │
│ lve reference "acraksmemilf46kr3qe.azurecr.io/retaildevcrews/ngsa-lr:beta": failed to do request: Head "https://acraksmemilf46kr3qe.azurecr.io/v2/retaildevcrews/ngsa-lr/manifests/beta": EOF  
 ```

Highly appreciate the help.

**Comment by ckittel** [comment]
Thank you @joaquinrz for bringing this to our attention. You are indeed correct that there some undesired behavior happening here.  The shared Private DNS Zone record is not behaving in the way that we originally intended.

Proposed solution:
Each regional resource group will now receive a Private DNS Zone resource for the shared container registry instance. Each Private DNS Zone resource will be attached only to their own local, regional vnet (instead of one shared to both vnets).  This will resolve the problem of only one region being able to route to the resolved DNS value for the Private Link-exposed ACR instance.

We'll see if we can get this addressed in about three weeks.
